set(OUT_NAME DSHCtl)

# 指定使用的 CMake 最低版本
cmake_minimum_required(VERSION 3.10)

# 定义工程名称
project(${OUT_NAME})

# 设置生成动态库
set(BUILD_SHARED_LIBS ON)

# 设置可执行程序输出的路径
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_CURRENT_SOURCE_DIR}/bin)
set(CMAKE_INSTALL_PREFIX ${CMAKE_CURRENT_SOURCE_DIR}/bin)
set(INSTALL_BIN_PATH ${CMAKE_CURRENT_SOURCE_DIR}/bin)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_ALLOW_LOOSE_LOOP_CONSTRUCTS ON)

# 设置MSVC编译相关设置
if(MSVC)
	# 设置默认编译类型为RelWithDebInfo
	set(CMAKE_BUILD_TYPE RelWithDebInfo)
	set(CMAKE_CONFIGURATION_TYPES "RelWithDebInfo" "Release")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} /MP /MD /O2 /Ob2 /DNDEBUG /utf-8")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS} /MP /MD /Zi /O2 /Ob1 /DNDEBUG /utf-8")
	# 取消.ilk文件生成(关闭增量编译)
	set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "/debug /INCREMENTAL:NO")
	set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "/debug")
endif(MSVC)

# SRC目录
set(ROOT_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Src)
# 根目录
set(ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR})
# 可执行程序bin目录
set(BIN_DIR ${ROOT_DIR}/bin)
# 库目录
set(LIB_DIR ${ROOT_DIR}/libs)
set(LIBRARY_OUTPUT_PATH ${LIB_DIR})

# 设置c++标准
set(CMAKE_CXX_STANDARD 17)

# 从环境变量查找qt
set(CMAKE_PREFIX_PATH $ENV{QTDIR})

# 查找Qt
find_package(Qt6 REQUIRED COMPONENTS
	Core
	Gui
	Widgets
	Network
)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BIN_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${BIN_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${BIN_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${LIB_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${LIB_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${LIB_DIR})

# 添加子目录
add_subdirectory(Src)
