set(OUT_NAME DSHCtl)

# 库目录
link_directories(${LIB_DIR})

# 搜索项目文件
file(GLOB HEADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)
file(GLOB SRC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
file(GLOB UI_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.ui)
file(GLOB RC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.rc)
file(GLOB QRC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.qrc)

qt6_add_resources(QRC_FILES ${QRC_FILES})

QT6_WRAP_UI(SRC_FILES ${UI_FILES})

add_executable(
	${OUT_NAME}
	${HEADER_FILES}
	${SRC_FILES}
	${RC_FILES}
	${QRC_FILES}
)

# 去除控制台窗口
SET_PROPERTY(TARGET ${OUT_NAME} PROPERTY LINK_FLAGS_RELEASE "/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup")
SET_PROPERTY(TARGET ${OUT_NAME} PROPERTY LINK_FLAGS_RELWITHDEBINFO "/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup")

target_link_libraries(
	${OUT_NAME}
	Qt6::Core
	Qt6::Gui
	Qt6::Widgets
	Qt6::Network
)
